name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ctest

  build-on-windows:

    runs-on: windows-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          ctest

  build-on-macos:

    runs-on: macos-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ctest
